### ISSUE TITLE
Width

### ISSUE THREAD

**Issue by evanzummeren** [cultuur-gif/expertisedag-gatsby#1]
Ik denk dat het mooier is om even een max full width aan te houden. Misschien kunnen we dat ook gewoon met percentages doen? Alles in een container van 80% vanaf laptop werkt denk ik net beter. Voelt nu net wat te lomp ofzo.

Ik zou ook twee kolommen behouden bij de keynote sprekers in het geval van tablet grootte. Misschien pas overgaan op een kolom op mobiel?

Ook de top en bottom margin bij de scheve koppen zijn nu veel te groot.

**Comment by Zaturrby** [comment]
We moeten even samen gaan kletsen hierover, typografie moet sowieso nog
fijner gedefinieerd. Welke widths bedoel je eigenlijk? Ik heb hem op ems
staan, dus altijd x letters breed.


On 16 April 2018 at 13:49:38, Erik van Zummeren (notifications@github.com)
wrote:

Ik denk dat het mooier is om even een max full width aan te houden.
Misschien kunnen we dat ook gewoon met percentages doen? Alles in een
container van 80% vanaf laptop werkt denk ik net beter. Voelt nu net wat te
lomp ofzo.

Ik zou ook twee kolommen behouden bij de keynote sprekers in het geval van
tablet grootte. Misschien pas overgaan op een kolom op mobiel?

Ook de top en bottom margin bij de scheve koppen zijn nu veel te groot.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cultuur-gif/expertisedag-gatsby/issues/1>, or mute the
thread
